### ISSUE TITLE
Please Release Version: [1.0.30001020,2)

### ISSUE THREAD

**Issue by riccardomerolla** [webjars/caniuse-lite#1]
It is a dependency for 
 "org.webjars.npm"   % "tailwindcss"                    % "1.1.3"

**Comment by jamesward** [comment]
For NPM WebJars you should be able to deploy them via https://www.webjars.org  Is that not working?

**Comment by riccardomerolla** [comment]
Sorry, solved, I've done some time ago and before I didn't remember what I've to do.

Thank you.
